/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuthRouteImport } from './routes/admin._auth'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as TiketCodeRouteImport } from './routes/tiket.$code'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth.dashboard'
import { Route as AdminAuthScanRouteImport } from './routes/admin._auth.scan'
import { Route as AdminAuthEventsIndexRouteImport } from './routes/admin._auth.events.index'
import { Route as AdminAuthEventsNewRouteImport } from './routes/admin._auth.events.new'
import { Route as AdminAuthEventsIdIndexRouteImport } from './routes/admin._auth.events.$id.index'
import { Route as AdminAuthEventsIdEditRouteImport } from './routes/admin._auth.events.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TiketCodeRoute = TiketCodeRouteImport.update({
  id: '/tiket/$code',
  path: '/tiket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthScanRoute = AdminAuthScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthEventsIndexRoute = AdminAuthEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthEventsNewRoute = AdminAuthEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthEventsIdIndexRoute = AdminAuthEventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthEventsIdEditRoute = AdminAuthEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tiket/$code': typeof TiketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/scan': typeof AdminAuthScanRoute
  '/admin/events/new': typeof AdminAuthEventsNewRoute
  '/admin/events/': typeof AdminAuthEventsIndexRoute
  '/admin/events/$id/edit': typeof AdminAuthEventsIdEditRoute
  '/admin/events/$id/': typeof AdminAuthEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tiket/$code': typeof TiketCodeRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/scan': typeof AdminAuthScanRoute
  '/admin/events/new': typeof AdminAuthEventsNewRoute
  '/admin/events': typeof AdminAuthEventsIndexRoute
  '/admin/events/$id/edit': typeof AdminAuthEventsIdEditRoute
  '/admin/events/$id': typeof AdminAuthEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tiket/$code': typeof TiketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/scan': typeof AdminAuthScanRoute
  '/admin/_auth/events/new': typeof AdminAuthEventsNewRoute
  '/admin/_auth/events/': typeof AdminAuthEventsIndexRoute
  '/admin/_auth/events/$id/edit': typeof AdminAuthEventsIdEditRoute
  '/admin/_auth/events/$id/': typeof AdminAuthEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/events/$slug'
    | '/tiket/$code'
    | '/admin/'
    | '/admin/dashboard'
    | '/admin/scan'
    | '/admin/events/new'
    | '/admin/events/'
    | '/admin/events/$id/edit'
    | '/admin/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/events/$slug'
    | '/tiket/$code'
    | '/admin/dashboard'
    | '/admin/scan'
    | '/admin/events/new'
    | '/admin/events'
    | '/admin/events/$id/edit'
    | '/admin/events/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/_auth'
    | '/admin/login'
    | '/events/$slug'
    | '/tiket/$code'
    | '/admin/'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/scan'
    | '/admin/_auth/events/new'
    | '/admin/_auth/events/'
    | '/admin/_auth/events/$id/edit'
    | '/admin/_auth/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  EventsSlugRoute: typeof EventsSlugRoute
  TiketCodeRoute: typeof TiketCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiket/$code': {
      id: '/tiket/$code'
      path: '/tiket/$code'
      fullPath: '/tiket/$code'
      preLoaderRoute: typeof TiketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/scan': {
      id: '/admin/_auth/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminAuthScanRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/events/': {
      id: '/admin/_auth/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminAuthEventsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/events/new': {
      id: '/admin/_auth/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminAuthEventsNewRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/events/$id/': {
      id: '/admin/_auth/events/$id/'
      path: '/events/$id'
      fullPath: '/admin/events/$id/'
      preLoaderRoute: typeof AdminAuthEventsIdIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/events/$id/edit': {
      id: '/admin/_auth/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminAuthEventsIdEditRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthScanRoute: typeof AdminAuthScanRoute
  AdminAuthEventsNewRoute: typeof AdminAuthEventsNewRoute
  AdminAuthEventsIndexRoute: typeof AdminAuthEventsIndexRoute
  AdminAuthEventsIdEditRoute: typeof AdminAuthEventsIdEditRoute
  AdminAuthEventsIdIndexRoute: typeof AdminAuthEventsIdIndexRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthScanRoute: AdminAuthScanRoute,
  AdminAuthEventsNewRoute: AdminAuthEventsNewRoute,
  AdminAuthEventsIndexRoute: AdminAuthEventsIndexRoute,
  AdminAuthEventsIdEditRoute: AdminAuthEventsIdEditRoute,
  AdminAuthEventsIdIndexRoute: AdminAuthEventsIdIndexRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  EventsSlugRoute: EventsSlugRoute,
  TiketCodeRoute: TiketCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
